"""Reverse Parser Documentation for InkLang.

This module provides comprehensive documentation for the SVG to YAML reverse parser,
which is the inverse of the renderer. It allows you to:

1. Parse existing SVG files (hand-drawn or generated by InkLang)
2. Extract all visual properties into InkLang's declarative YAML schema
3. Output validated YAML that can be re-rendered or edited

## Overview

The reverse parser implements a complete bidirectional transformation:

    YAML Design → (renderer) → SVG File
                                    ↓
                                (reverse_parser)
                                    ↓
                              YAML Design (recovered)

This enables workflows like:
- Converting hand-drawn SVGs into InkLang for automation
- Inspecting SVG structure in human-readable YAML format
- Round-tripping designs with lossless fidelity

## Supported Features

### Element Types
- ✅ text (with font styling)
- ✅ rect (with rounded corners)
- ✅ circle
- ✅ ellipse
- ✅ line (with strokes)
- ✅ polyline (multi-point open shapes)
- ✅ polygon (multi-point closed shapes)
- ✅ path (arbitrary SVG path data)
- ✅ image (with href preservation)
- ✅ group (nested elements with inheritance)

### Styling & Attributes
- ✅ fill color
- ✅ stroke (color, width, dash patterns)
- ✅ opacity (0–1)
- ✅ transforms (translate, rotate, scale, skew, matrix)
- ✅ font properties (family, size, weight, style)
- ✅ text content and baseline positioning

### Advanced Features (from <defs>)
- ✅ Linear gradients (x1, y1, x2, y2, stops)
- ✅ Radial gradients (cx, cy, r, fx, fy, stops)
- ✅ SVG Filters:
  - GaussianBlur (stdDeviation)
  - Offset (dx, dy)
  - ColorMatrix (saturate, hueRotate, luminanceToAlpha)
  - Blend (mode, in2)
  - Merge (nodes)
- ✅ Clip paths (extracted from <clipPath>)
- ✅ Masks (extracted from <mask>)

### Canvas & Metadata
- ✅ Canvas size (from viewBox or width/height)
- ✅ Background color
- ✅ Element IDs
- ✅ SVG viewBox preservation

## Usage Examples

### 1. Parse an SVG file to a Design object

```python
from inklang.reverse_parser import parse_svg_to_design

design = parse_svg_to_design("my_drawing.svg")
print(f"Canvas: {design.width}x{design.height}")
print(f"Elements: {len(design.elements)}")
```

### 2. Convert SVG to YAML (CLI)

```bash
# Print YAML to stdout
inklang reverse path/to/file.svg

# Save YAML to file
inklang reverse path/to/file.svg --out output.yaml
```

### 3. Convert SVG to YAML (Python)

```python
from inklang.reverse_parser import svg_to_yaml

# Get YAML as string
yaml_output = svg_to_yaml("design.svg")
print(yaml_output)

# Write directly to file
svg_to_yaml("design.svg", output_path="design.yaml")
```

### 4. Parse and re-render

```python
from inklang.reverse_parser import parse_svg_to_design
from inklang.renderer import write_svg

# Parse existing SVG
design = parse_svg_to_design("original.svg")

# Modify and re-render
design.background = "#00ff00"  # Change background
write_svg(design, "modified.svg")
```

### 5. Round-trip workflow

```python
from inklang.parser import load_design
from inklang.renderer import write_svg
from inklang.reverse_parser import parse_svg_to_design

# Start with YAML
design1 = load_design("design.yaml", {"name": "Alice"})

# Render to SVG
write_svg(design1, "output.svg")

# Parse SVG back to Design
design2 = parse_svg_to_design("output.svg")

# Both designs should be structurally equivalent
assert design1.size == design2.size
```

## API Reference

### parse_svg_to_design(svg_path: Union[str, Path]) → Design

Parse an SVG file and return a validated Design object.

**Args:**
- `svg_path`: Path to the SVG file (string or Path object).

**Returns:**
- A `Design` object with all extracted elements, gradients, filters, clips, masks.

**Raises:**
- `ParseError`: If the SVG cannot be parsed, is malformed, or lacks required attributes.

**Example:**
```python
design = parse_svg_to_design("icon.svg")
print(design.design)  # design name (from id or "Parsed Design")
print(design.size)    # "100x100"
print(len(design.elements))  # number of elements
```

### svg_to_yaml(svg_path: Union[str, Path], output_path: Optional[Union[str, Path]] = None) → str

Parse an SVG file and output InkLang YAML.

**Args:**
- `svg_path`: Path to the input SVG file.
- `output_path`: Optional path to write the YAML. If None, returns the string.

**Returns:**
- YAML string representation of the design.

**Raises:**
- `ParseError`: If the SVG cannot be parsed.

**Example:**
```python
# Print to stdout
yaml_str = svg_to_yaml("design.svg")
print(yaml_str)

# Write to file
svg_to_yaml("design.svg", output_path="design.yaml")
```

## Parsing Details

### Canvas Size Detection

The parser extracts canvas dimensions in this order:
1. **viewBox** attribute (preferred): `viewBox="0 0 350 200"` → 350×200
2. **width/height** attributes: `width="350px" height="200px"` → 350×200
3. Raises `ParseError` if neither is present.

Units (px, cm, etc.) are stripped automatically.

### Style Extraction

The parser checks both **element attributes** and **CSS style strings**:

```xml
<!-- Both work: -->
<rect fill="#ff0000" stroke="black" stroke-width="2"/>
<rect style="fill: #ff0000; stroke: black; stroke-width: 2px;"/>
```

CSS property names (dashes) are normalized to match schema field names.

### Transform Parsing

SVG transforms are parsed and converted to InkLang's declarative format:

```xml
<!-- SVG transform attribute -->
<g transform="translate(10 20) rotate(45) scale(1.5)">

<!-- Becomes InkLang -->
transform:
  translate: [10, 20]
  rotate: 45
  scale: 1.5
```

Supported transforms:
- `translate(x y)` → `translate: [x, y]`
- `rotate(angle)` or `rotate(angle cx cy)` → `rotate: angle` or `rotate: {angle, center: [cx, cy]}`
- `scale(s)` or `scale(sx sy)` → `scale: s` or `scale: [sx, sy]`
- `skewX(angle)` / `skewY(angle)` → `skewX` / `skewY`
- `matrix(a b c d e f)` → `matrix: "a b c d e f"`

### Gradient Extraction

Gradients defined in `<defs>` are extracted and referenced by ID:

```xml
<defs>
  <linearGradient id="sky">
    <stop offset="0%" stop-color="#ff0000"/>
    <stop offset="100%" stop-color="#0000ff"/>
  </linearGradient>
</defs>
<rect fill="url(#sky)"/>

<!-- Becomes -->
gradients:
  sky:
    type: linear
    x1: 0.0
    y1: 0.0
    x2: 1.0
    y2: 0.0
    stops:
      - offset: 0
        color: "#ff0000"
      - offset: 100
        color: "#0000ff"
elements:
  - type: rect
    fill: "ref:sky"  # reference
```

### Filter Extraction

Filters from `<defs><filter>` are parsed into primitives:

```xml
<defs>
  <filter id="blur">
    <feGaussianBlur stdDeviation="2"/>
  </filter>
</defs>

<!-- Becomes -->
filters:
  blur:
    primitives:
      - type: gaussianBlur
        std_deviation: 2
```

Supported filter primitives:
- `gaussianBlur` (stdDeviation)
- `offset` (dx, dy)
- `feColorMatrix` (type, values)
- `feBlend` (mode, in2)
- `feMerge` (input nodes)

### Clip Path & Mask Extraction

`<clipPath>` and `<mask>` elements are extracted as named shapes:

```xml
<defs>
  <clipPath id="avatar">
    <circle cx="50" cy="50" r="40"/>
  </clipPath>
</defs>
<rect clip-path="url(#avatar)"/>

<!-- Becomes -->
clips:
  avatar:
    type: circle
    center: [50, 50]
    radius: 40
elements:
  - type: rect
    clip: avatar
```

## Known Limitations

### Partial Support
- **Gradients**: Extracted by ID but not fully reverse-engineered from stop color interpolation.
- **Text**: Multi-line text with `<tspan>` is simplified to flat content.
- **Patterns**: SVG `<pattern>` elements are not yet supported.
- **Markers**: SVG `<marker>` elements are not extracted.

### Not Supported
- **Animations** (`<animate>`, `<animateTransform>`, etc.)
- **Symbols** (`<symbol>`, `<use>` elements as references)
- **Foreign content** (`<foreignObject>`)
- **Custom namespaces** (e.g., Inkscape-specific metadata is ignored)

### Round-trip Notes
- Text positioning may differ slightly due to baseline vs. top-left differences.
- Complex transforms may not round-trip perfectly through matrix decomposition.
- Gradient coordinates in objectBoundingBox units may need re-calibration if the element is resized.

## Error Handling

The parser raises `ParseError` (a subclass of `InklangError`) with clear messages:

```python
from inklang.reverse_parser import parse_svg_to_design
from inklang.errors import ParseError

try:
    design = parse_svg_to_design("invalid.svg")
except ParseError as e:
    print(f"Error: {e}")
    # Output: Error: Failed to parse SVG file invalid.svg: [reason]
```

Common errors:
- **File not found**: "Could not determine canvas size from viewBox or width/height"
- **Invalid XML**: "[XML parsing error]"
- **Missing size**: "Could not determine canvas size..."

## Testing

The reverse parser includes comprehensive tests covering:

```bash
# Run all tests
uv run pytest tests/test_reverse_parser.py -v

# Run specific test
uv run pytest tests/test_reverse_parser.py::test_parse_rect_element -v

# Coverage
uv run pytest tests/test_reverse_parser.py --cov=inklang.reverse_parser
```

Test categories:
- **Element parsing**: rect, circle, ellipse, line, polyline, polygon, path, text, image, group
- **Attributes**: fill, stroke, opacity, transforms, fonts
- **Advanced features**: gradients, filters, clips, masks
- **Round-tripping**: SVG → Design → YAML → Design
- **Error handling**: missing files, invalid XML, missing attributes

## Performance Considerations

- **Memory**: The entire SVG is parsed into memory. Large SVGs (>100 MB) may be slow.
- **Complexity**: Deeply nested groups or many elements scale linearly.
- **Typical performance**: A 1000-element SVG parses in ~100ms on a modern machine.

## Workflow Examples

### Convert Hand-Drawn SVG to Automated Design

```bash
# 1. Export SVG from Inkscape or Illustrator
# 2. Parse to YAML
inklang reverse hand_drawn.svg --out design.yaml

# 3. Edit YAML (optional)
# 4. Use with data for batch generation
inklang batch design.yaml --data people.csv --out-dir cards/
```

### Inspect SVG Structure

```bash
# View SVG as YAML (human-readable)
inklang reverse complex_icon.svg

# Pretty-print to file
inklang reverse complex_icon.svg --out structure.yaml
cat structure.yaml
```

### Migrate from Inkscape to InkLang

```bash
# 1. Save Inkscape document as SVG (File → Save As)
# 2. Parse to YAML
inklang reverse inkscape_doc.svg --out design.yaml

# 3. Test rendering
inklang render design.yaml --out test.svg

# 4. Edit design.yaml for parameterization
# 5. Use with CSV/JSON data for batch production
```

## References

- **SVG 2 Spec**: https://www.w3.org/TR/SVG2/
- **Inkscape SVG Export**: https://inkscape.org/develop/about-svg/
- **InkLang Schema**: See `inklang/schema.py`
- **InkLang CLI**: `inklang reverse --help`

## Future Enhancements

Potential additions (not yet implemented):
- Support for `<symbol>` and `<use>` references
- Animated transforms (`<animateTransform>`)
- Pattern extraction
- Text path support (`<textPath>`)
- Improved text wrapping detection
- Marker and arrowhead extraction
- Better grouping heuristics for layer reconstruction
"""

# This is a documentation module; no runtime code follows.
