"""Reverse parser: convert SVG to InkLang YAML.

This module provides the inverse transformation of the renderer: given an SVG
file (either hand-drawn or generated by InkLang), parse it back into a validated
Design object and serialize it as YAML.

The parser extracts:
- Canvas dimensions and viewBox as a ``size`` string
- Element hierarchy and attributes (text, rect, circle, ellipse, line, polyline,
  polygon, path, image, and groups)
- Styles (fill, stroke, font properties, opacity, transforms)
- Gradients, filters, masks, and clip-paths from <defs>
- References to gradients, clips, filters, and masks
- Stroke dashes and other advanced SVG features

Supported SVG features (following Inkscape spec):
- All basic shapes: rect, circle, ellipse, line, polyline, polygon, path
- Text with font styling (family, size, weight, style)
- Images
- Groups (nested elements)
- Strokes with width, color, and dash patterns
- Opacity and transforms
- Linear and radial gradients
- SVG filters (Gaussian blur, offset, color matrix, blend, merge)
- Clip paths and masks

The main entry point is :func:`parse_svg_to_design`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import yaml
from lxml import etree

from .errors import ParseError
from .schema import (
    BlendPrimitive,
    CircleElement,
    CircleGeo,
    ColorMatrixPrimitive,
    Design,
    EllipseElement,
    EllipseGeo,
    Element,
    ElementBase,
    FilterRegion,
    FilterSpec,
    Font,
    GaussianBlurPrimitive,
    GroupElement,
    ImageElement,
    LineElement,
    LinearGradientSpec,
    MaskSpec,
    MergePrimitive,
    OffsetPrimitive,
    PathElementModel,
    PathGeo,
    PolygonElement,
    PolygonGeo,
    PolylineElement,
    RadialGradientSpec,
    RectElement,
    RectGeo,
    StopSpec,
    Stroke,
    TextElement as TextModel,
    TransformSpec,
)


# SVG namespace for proper element lookup
SVG_NS = {"svg": "http://www.w3.org/2000/svg", "xlink": "http://www.w3.org/1999/xlink"}


def _extract_viewbox_and_size(svg_root: Any) -> tuple[float, float]:
    """Extract canvas dimensions from viewBox or width/height attributes.
    
    Returns (width, height) as floats. Prefers viewBox if present.
    """
    viewbox = svg_root.get("viewBox")
    if viewbox:
        parts = viewbox.split()
        if len(parts) >= 4:
            return float(parts[2]), float(parts[3])

    width = svg_root.get("width")
    height = svg_root.get("height")
    if width and height:
        # Remove units (px, cm, etc.)
        w_str = str(width).rstrip("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ%")
        h_str = str(height).rstrip("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ%")
        try:
            return float(w_str), float(h_str)
        except ValueError:
            pass

    raise ParseError("Could not determine canvas size from viewBox or width/height")


def _parse_style_dict(style_str: Optional[str]) -> Dict[str, str]:
    """Parse a CSS style string into a dict.
    
    Example: "fill: #fff; stroke: #000; stroke-width: 2px" ->
    {"fill": "#fff", "stroke": "#000", "stroke-width": "2px"}
    """
    result = {}
    if not style_str:
        return result
    for item in style_str.split(";"):
        item = item.strip()
        if ":" in item:
            key, val = item.split(":", 1)
            result[key.strip()] = val.strip()
    return result


def _get_paint_color(element: Any, attr: str, style_dict: Dict[str, str]) -> Optional[str]:
    """Extract a paint color from element attributes or style.
    
    Checks (in order): element attribute, style dict, returns None if neither.
    Normalizes 'none' to None.
    """
    # Check direct attribute first
    value = element.get(attr)
    if value and value.lower() != "none":
        return value

    # Check style dict (CSS names use dashes)
    style_key = attr if attr in style_dict else attr.replace("_", "-")
    value = style_dict.get(style_key)
    if value and value.lower() != "none":
        return value

    return None


def _get_numeric_style(
    element: Any, style_dict: Dict[str, str], attr: str, default: Optional[float] = None
) -> Optional[float]:
    """Extract a numeric value from element or style, stripping units."""
    # Try element attribute
    val = element.get(attr)
    if val:
        try:
            return float(str(val).rstrip("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ%"))
        except ValueError:
            pass

    # Try style dict (CSS names use dashes)
    style_key = attr if attr in style_dict else attr.replace("_", "-")
    val = style_dict.get(style_key)
    if val:
        try:
            return float(str(val).rstrip("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ%"))
        except ValueError:
            pass

    return default


def _extract_stroke(element: Any, style_dict: Dict[str, str]) -> Optional[Stroke]:
    """Extract stroke from element attributes and style, or return None if no stroke."""
    color = _get_paint_color(element, "stroke", style_dict)
    if not color:
        return None

    width = _get_numeric_style(element, style_dict, "stroke-width", default=1.0)
    dash_str = style_dict.get("stroke-dasharray")
    dash = None
    if dash_str:
        try:
            dash = [float(v.strip()) for v in dash_str.split()]
        except ValueError:
            pass

    return Stroke(color=color, width=width or 1.0, dash=dash)


def _parse_transform_string(transform_str: Optional[str]) -> Optional[TransformSpec]:
    """Parse SVG transform attribute into a TransformSpec.
    
    Handles translate, rotate, scale, skewX, skewY, matrix.
    This is a simplified parser; complex nested transforms may not round-trip perfectly.
    """
    if not transform_str:
        return None

    transform_str = transform_str.strip()
    spec_dict = {}

    # Extract individual transforms using regex-like parsing
    import re

    # Pattern: func_name(args)
    pattern = r"(\w+)\s*\(\s*([^)]+)\)"
    for match in re.finditer(pattern, transform_str):
        func_name = match.group(1).lower()
        args_str = match.group(2).strip()
        try:
            args = [float(x.strip()) for x in args_str.split(",") if x.strip()]
        except ValueError:
            continue

        if func_name == "translate" and len(args) >= 1:
            spec_dict["translate"] = args[:2] if len(args) >= 2 else [args[0], 0]
        elif func_name == "rotate" and len(args) >= 1:
            if len(args) == 1:
                spec_dict["rotate"] = args[0]
            elif len(args) == 3:
                spec_dict["rotate"] = {"angle": args[0], "center": [args[1], args[2]]}
        elif func_name == "scale" and len(args) >= 1:
            spec_dict["scale"] = args[0] if len(args) == 1 else args[:2]
        elif func_name == "skewx" and len(args) >= 1:
            spec_dict["skewX"] = args[0]
        elif func_name == "skewy" and len(args) >= 1:
            spec_dict["skewY"] = args[0]
        elif func_name == "matrix" and len(args) >= 6:
            spec_dict["matrix"] = " ".join(str(a) for a in args)

    if not spec_dict:
        return None

    return TransformSpec(**spec_dict)


def _extract_base_attrs(element: Any, style_dict: Dict[str, str]) -> Dict[str, Any]:
    """Extract shared ElementBase attributes: id, opacity, transform, clip, filter, mask."""
    attrs = {}

    if element.get("id"):
        attrs["id"] = element.get("id")

    opacity = _get_numeric_style(element, style_dict, "opacity")
    if opacity is not None and opacity != 1.0:
        attrs["opacity"] = opacity

    transform = element.get("transform")
    if transform:
        transform_spec = _parse_transform_string(transform)
        if transform_spec:
            attrs["transform"] = transform_spec

    clip_path = element.get("clip-path")
    if clip_path:
        # Extract ID from url(#id)
        import re
        match = re.search(r"url\(#([^)]+)\)", clip_path)
        if match:
            attrs["clip"] = match.group(1)

    mask_attr = element.get("mask")
    if mask_attr:
        import re
        match = re.search(r"url\(#([^)]+)\)", mask_attr)
        if match:
            attrs["mask"] = match.group(1)

    filter_attr = style_dict.get("filter")
    if filter_attr:
        import re
        match = re.search(r"url\(#([^)]+)\)", filter_attr)
        if match:
            attrs["filter"] = match.group(1)

    return attrs


def _parse_text_element(element: Any, style_dict: Dict[str, str]) -> Optional[TextModel]:
    """Parse a <text> element into a TextModel."""
    try:
        x = float(element.get("x", 0))
        y = float(element.get("y", 0))
        content = "".join(element.itertext()) or ""

        color = _get_paint_color(element, "fill", style_dict) or "#000000"

        font_family = style_dict.get("font-family", "Arial")
        font_size = _get_numeric_style(element, style_dict, "font-size", default=16)
        font_weight = style_dict.get("font-weight")
        font_style = style_dict.get("font-style")

        font = Font(
            family=font_family,
            size=int(font_size),
            weight=font_weight,
            style=font_style,
        )

        return TextModel(
            type="text",
            content=content,
            position=[x, y],
            color=color,
            font=font,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <text> element: {e}")


def _parse_rect_element(element: Any, style_dict: Dict[str, str]) -> Optional[RectElement]:
    """Parse a <rect> element into a RectElement."""
    try:
        x = float(element.get("x", 0))
        y = float(element.get("y", 0))
        width = float(element.get("width", 0))
        height = float(element.get("height", 0))

        fill = _get_paint_color(element, "fill", style_dict) or "#000000"
        stroke = _extract_stroke(element, style_dict)

        corner_radius = None
        rx = element.get("rx")
        if rx:
            try:
                corner_radius = float(rx)
            except ValueError:
                pass

        return RectElement(
            type="rect",
            position=[x, y],
            size=[width, height],
            fill=fill,
            stroke=stroke,
            corner_radius=corner_radius,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <rect> element: {e}")


def _parse_circle_element(element: Any, style_dict: Dict[str, str]) -> Optional[CircleElement]:
    """Parse a <circle> element into a CircleElement."""
    try:
        cx = float(element.get("cx", 0))
        cy = float(element.get("cy", 0))
        radius = float(element.get("r", 0))

        fill = _get_paint_color(element, "fill", style_dict) or "#000000"
        stroke = _extract_stroke(element, style_dict)

        return CircleElement(
            type="circle",
            center=[cx, cy],
            radius=radius,
            fill=fill,
            stroke=stroke,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <circle> element: {e}")


def _parse_ellipse_element(element: Any, style_dict: Dict[str, str]) -> Optional[EllipseElement]:
    """Parse an <ellipse> element into an EllipseElement."""
    try:
        cx = float(element.get("cx", 0))
        cy = float(element.get("cy", 0))
        rx = float(element.get("rx", 0))
        ry = float(element.get("ry", 0))

        fill = _get_paint_color(element, "fill", style_dict) or "#000000"
        stroke = _extract_stroke(element, style_dict)

        return EllipseElement(
            type="ellipse",
            center=[cx, cy],
            radii=[rx, ry],
            fill=fill,
            stroke=stroke,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <ellipse> element: {e}")


def _parse_line_element(element: Any, style_dict: Dict[str, str]) -> Optional[LineElement]:
    """Parse a <line> element into a LineElement."""
    try:
        x1 = float(element.get("x1", 0))
        y1 = float(element.get("y1", 0))
        x2 = float(element.get("x2", 0))
        y2 = float(element.get("y2", 0))

        stroke = _extract_stroke(element, style_dict)
        if not stroke:
            # Line requires stroke; create a default black stroke
            stroke = Stroke(color="#000000", width=1)

        return LineElement(
            type="line",
            start=[x1, y1],
            end=[x2, y2],
            stroke=stroke,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <line> element: {e}")


def _parse_polyline_element(element: Any, style_dict: Dict[str, str]) -> Optional[PolylineElement]:
    """Parse a <polyline> element into a PolylineElement."""
    try:
        points_str = element.get("points", "")
        points = []
        for pair in points_str.split():
            if "," in pair:
                x, y = pair.split(",")
                points.append([float(x), float(y)])

        stroke = _extract_stroke(element, style_dict)
        if not stroke:
            stroke = Stroke(color="#000000", width=1)

        fill = _get_paint_color(element, "fill", style_dict)

        return PolylineElement(
            type="polyline",
            points=points,
            stroke=stroke,
            fill=fill,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <polyline> element: {e}")


def _parse_polygon_element(element: Any, style_dict: Dict[str, str]) -> Optional[PolygonElement]:
    """Parse a <polygon> element into a PolygonElement."""
    try:
        points_str = element.get("points", "")
        points = []
        for pair in points_str.split():
            if "," in pair:
                x, y = pair.split(",")
                points.append([float(x), float(y)])

        fill = _get_paint_color(element, "fill", style_dict) or "#000000"
        stroke = _extract_stroke(element, style_dict)

        return PolygonElement(
            type="polygon",
            points=points,
            fill=fill,
            stroke=stroke,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <polygon> element: {e}")


def _parse_path_element(element: Any, style_dict: Dict[str, str]) -> Optional[PathElementModel]:
    """Parse a <path> element into a PathElementModel."""
    try:
        d = element.get("d", "")
        fill = _get_paint_color(element, "fill", style_dict) or "#000000"
        stroke = _extract_stroke(element, style_dict)

        return PathElementModel(
            type="path",
            d=d,
            fill=fill,
            stroke=stroke,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <path> element: {e}")


def _parse_image_element(element: Any, style_dict: Dict[str, str]) -> Optional[ImageElement]:
    """Parse an <image> element into an ImageElement."""
    try:
        x = float(element.get("x", 0))
        y = float(element.get("y", 0))
        width = float(element.get("width", 0))
        height = float(element.get("height", 0))

        # Prefer href (SVG2) over xlink:href (classic)
        src = element.get("href") or element.get("{http://www.w3.org/1999/xlink}href", "")

        opacity = _get_numeric_style(element, style_dict, "opacity")

        attrs = _extract_base_attrs(element, style_dict)
        if opacity is not None:
            attrs["opacity"] = opacity

        return ImageElement(
            type="image",
            src=src,
            position=[x, y],
            size=[width, height],
            **attrs,
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <image> element: {e}")


def _parse_group_element(element: Any) -> Optional[GroupElement]:
    """Parse a <g> (group) element into a GroupElement, recursively parsing children."""
    try:
        style_dict = _parse_style_dict(element.get("style"))
        children = []

        for child in element:
            # Skip non-element nodes and <defs>
            if not isinstance(child.tag, str):
                continue
            tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag
            if tag == "defs":
                continue

            parsed = _parse_element(child)
            if parsed:
                children.append(parsed)

        return GroupElement(
            type="group",
            children=children,
            **_extract_base_attrs(element, style_dict),
        )
    except Exception as e:
        raise ParseError(f"Failed to parse <g> (group) element: {e}")


def _parse_element(element: Any) -> Optional[Element]:
    """Dispatch an element to its parser based on tag name."""
    if not isinstance(element.tag, str):
        return None

    tag = element.tag.split("}")[-1] if "}" in element.tag else element.tag
    style_dict = _parse_style_dict(element.get("style"))

    # Skip background rectangles with id="background"
    if tag == "rect" and element.get("id") == "background":
        return None

    if tag == "text":
        return _parse_text_element(element, style_dict)
    elif tag == "rect":
        return _parse_rect_element(element, style_dict)
    elif tag == "circle":
        return _parse_circle_element(element, style_dict)
    elif tag == "ellipse":
        return _parse_ellipse_element(element, style_dict)
    elif tag == "line":
        return _parse_line_element(element, style_dict)
    elif tag == "polyline":
        return _parse_polyline_element(element, style_dict)
    elif tag == "polygon":
        return _parse_polygon_element(element, style_dict)
    elif tag == "path":
        return _parse_path_element(element, style_dict)
    elif tag == "image":
        return _parse_image_element(element, style_dict)
    elif tag == "g":
        return _parse_group_element(element)
    else:
        return None


def _extract_gradients(defs: Any) -> Dict[str, Any]:
    """Extract linear and radial gradients from <defs> element."""
    gradients = {}

    for child in defs:
        if not isinstance(child.tag, str):
            continue
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag

        if tag == "linearGradient":
            grad_id = child.get("id")
            if grad_id:
                x1 = float(child.get("x1", 0))
                y1 = float(child.get("y1", 0))
                x2 = float(child.get("x2", 1))
                y2 = float(child.get("y2", 0))
                stops = []

                for stop in child:
                    stop_tag = stop.tag.split("}")[-1] if "}" in stop.tag else stop.tag
                    if stop_tag == "stop":
                        offset = float(stop.get("offset", 0).rstrip("%"))
                        stop_color = stop.get("stop-color", "#000000")
                        stop_opacity = float(stop.get("stop-opacity", 1))
                        stops.append(StopSpec(offset=offset, color=stop_color, opacity=stop_opacity))

                if stops:
                    gradients[grad_id] = LinearGradientSpec(
                        type="linear",
                        x1=x1,
                        y1=y1,
                        x2=x2,
                        y2=y2,
                        stops=stops,
                    )

        elif tag == "radialGradient":
            grad_id = child.get("id")
            if grad_id:
                cx = float(child.get("cx", 0.5))
                cy = float(child.get("cy", 0.5))
                r = float(child.get("r", 0.5))
                fx = child.get("fx")
                fy = child.get("fy")

                stops = []
                for stop in child:
                    stop_tag = stop.tag.split("}")[-1] if "}" in stop.tag else stop.tag
                    if stop_tag == "stop":
                        offset = float(stop.get("offset", 0).rstrip("%"))
                        stop_color = stop.get("stop-color", "#000000")
                        stop_opacity = float(stop.get("stop-opacity", 1))
                        stops.append(StopSpec(offset=offset, color=stop_color, opacity=stop_opacity))

                if stops:
                    grad_dict = {
                        "type": "radial",
                        "cx": cx,
                        "cy": cy,
                        "r": r,
                        "stops": stops,
                    }
                    if fx:
                        grad_dict["fx"] = float(fx)
                    if fy:
                        grad_dict["fy"] = float(fy)
                    gradients[grad_id] = RadialGradientSpec(**grad_dict)

    return gradients


def _extract_clip_paths(defs: Any) -> Dict[str, Any]:
    """Extract clip paths from <defs> element (simplified parsing)."""
    clips = {}
    
    for child in defs:
        if not isinstance(child.tag, str):
            continue
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag

        if tag == "clipPath":
            clip_id = child.get("id")
            if clip_id:
                # For now, extract the first shape from the clip path
                for shape in child:
                    if not isinstance(shape.tag, str):
                        continue
                    shape_tag = shape.tag.split("}")[-1] if "}" in shape.tag else shape.tag
                    style_dict = _parse_style_dict(shape.get("style"))

                    if shape_tag == "rect":
                        x = float(shape.get("x", 0))
                        y = float(shape.get("y", 0))
                        width = float(shape.get("width", 0))
                        height = float(shape.get("height", 0))
                        fill = _get_paint_color(shape, "fill", style_dict)
                        stroke = _extract_stroke(shape, style_dict)

                        clips[clip_id] = RectGeo(
                            type="rect",
                            position=[x, y],
                            size=[width, height],
                            fill=fill,
                            stroke=stroke,
                        )
                        break

                    elif shape_tag == "circle":
                        cx = float(shape.get("cx", 0))
                        cy = float(shape.get("cy", 0))
                        radius = float(shape.get("r", 0))
                        fill = _get_paint_color(shape, "fill", style_dict)
                        stroke = _extract_stroke(shape, style_dict)

                        clips[clip_id] = CircleGeo(
                            type="circle",
                            center=[cx, cy],
                            radius=radius,
                            fill=fill,
                            stroke=stroke,
                        )
                        break

    return clips


def _extract_filters(defs: Any) -> Dict[str, Any]:
    """Extract SVG filters from <defs> element (simplified parsing)."""
    filters = {}

    for child in defs:
        if not isinstance(child.tag, str):
            continue
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag

        if tag == "filter":
            filter_id = child.get("id")
            if filter_id:
                primitives = []

                for prim in child:
                    if not isinstance(prim.tag, str):
                        continue
                    prim_tag = prim.tag.split("}")[-1] if "}" in prim.tag else prim.tag

                    if prim_tag == "feGaussianBlur":
                        std_dev = prim.get("stdDeviation", "1")
                        try:
                            std_vals = [float(v) for v in std_dev.split()]
                            std_dev_val = std_vals if len(std_vals) > 1 else std_vals[0]
                        except ValueError:
                            std_dev_val = 1.0
                        primitives.append(GaussianBlurPrimitive(type="gaussianBlur", std_deviation=std_dev_val))

                    elif prim_tag == "feOffset":
                        dx = float(prim.get("dx", 0))
                        dy = float(prim.get("dy", 0))
                        primitives.append(OffsetPrimitive(type="offset", dx=dx, dy=dy))

                    elif prim_tag == "feColorMatrix":
                        mode = prim.get("type", "saturate")
                        values = prim.get("values")
                        primitives.append(ColorMatrixPrimitive(type="colorMatrix", mode=mode, values=values))

                    elif prim_tag == "feBlend":
                        mode = prim.get("mode", "normal")
                        in2 = prim.get("in2", "SourceGraphic")
                        primitives.append(BlendPrimitive(type="blend", mode=mode, in2=in2))

                    elif prim_tag == "feMerge":
                        nodes = []
                        for merge_node in prim:
                            node_tag = merge_node.tag.split("}")[-1] if "}" in merge_node.tag else merge_node.tag
                            if node_tag == "feMergeNode":
                                in_attr = merge_node.get("in", "SourceGraphic")
                                nodes.append(in_attr)
                        primitives.append(MergePrimitive(type="merge", nodes=nodes))

                if primitives:
                    filters[filter_id] = FilterSpec(primitives=primitives)

    return filters


def _extract_masks(defs: Any) -> Dict[str, Any]:
    """Extract SVG masks from <defs> element (simplified parsing)."""
    masks = {}

    for child in defs:
        if not isinstance(child.tag, str):
            continue
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag

        if tag == "mask":
            mask_id = child.get("id")
            if mask_id:
                mask_type = child.get("mask-type")
                shapes = []

                for shape in child:
                    if not isinstance(shape.tag, str):
                        continue
                    shape_tag = shape.tag.split("}")[-1] if "}" in shape.tag else shape.tag
                    style_dict = _parse_style_dict(shape.get("style"))

                    if shape_tag == "rect":
                        x = float(shape.get("x", 0))
                        y = float(shape.get("y", 0))
                        width = float(shape.get("width", 0))
                        height = float(shape.get("height", 0))
                        fill = _get_paint_color(shape, "fill", style_dict)
                        stroke = _extract_stroke(shape, style_dict)

                        shapes.append(RectGeo(
                            type="rect",
                            position=[x, y],
                            size=[width, height],
                            fill=fill,
                            stroke=stroke,
                        ))

                    elif shape_tag == "circle":
                        cx = float(shape.get("cx", 0))
                        cy = float(shape.get("cy", 0))
                        radius = float(shape.get("r", 0))
                        fill = _get_paint_color(shape, "fill", style_dict)
                        stroke = _extract_stroke(shape, style_dict)

                        shapes.append(CircleGeo(
                            type="circle",
                            center=[cx, cy],
                            radius=radius,
                            fill=fill,
                            stroke=stroke,
                        ))

                if shapes:
                    masks[mask_id] = MaskSpec(type=mask_type, shapes=shapes)

    return masks


def parse_svg_to_design(svg_path: Union[str, Path]) -> Design:
    """Parse an SVG file and return a Design object.

    Args:
        svg_path: Path to the SVG file.

    Returns:
        A validated Design object with full support for:
        - All SVG element types (shapes, text, images, groups)
        - Styling (fill, stroke, opacity, transforms)
        - Gradients (linear and radial)
        - Filters (Gaussian blur, offset, color matrix, blend, merge)
        - Clip paths and masks

    Raises:
        ParseError: If the SVG cannot be parsed or is malformed.
    """
    try:
        tree = etree.parse(str(svg_path))
        root = tree.getroot()
    except Exception as e:
        raise ParseError(f"Failed to parse SVG file {svg_path}: {e}")

    try:
        width, height = _extract_viewbox_and_size(root)
        size_str = f"{int(width)}x{int(height)}"
    except Exception as e:
        raise ParseError(f"Failed to extract canvas size: {e}")

    # Extract background color if present
    background = None
    style_dict = _parse_style_dict(root.get("style"))
    bg = root.get("fill") or style_dict.get("fill")
    if bg and bg.lower() != "none":
        background = bg

    # Extract definitions (gradients, filters, clips, masks)
    gradients = {}
    filters = {}
    clips = {}
    masks = {}

    for defs in root.findall(".//{http://www.w3.org/2000/svg}defs"):
        gradients.update(_extract_gradients(defs))
        filters.update(_extract_filters(defs))
        clips.update(_extract_clip_paths(defs))
        masks.update(_extract_masks(defs))

    # Also check for non-namespaced defs
    for defs in root.findall(".//defs"):
        gradients.update(_extract_gradients(defs))
        filters.update(_extract_filters(defs))
        clips.update(_extract_clip_paths(defs))
        masks.update(_extract_masks(defs))

    # Parse elements (skip <defs> and any non-visual elements)
    elements: List[Element] = []
    for child in root:
        if not isinstance(child.tag, str):
            continue
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag
        if tag == "defs":
            continue
        parsed = _parse_element(child)
        if parsed:
            elements.append(parsed)

    design_name = root.get("id") or "Parsed Design"

    return Design(
        design=design_name,
        size=size_str,
        background=background,
        gradients=gradients,
        filters=filters,
        clips=clips,
        masks=masks,
        elements=elements,
    )


def svg_to_yaml(svg_path: Union[str, Path], output_path: Optional[Union[str, Path]] = None) -> str:
    """Parse an SVG file and output InkLang YAML.

    Args:
        svg_path: Path to the input SVG file.
        output_path: Optional path to write the YAML. If None, returns the YAML string.

    Returns:
        YAML string representation of the design.

    Raises:
        ParseError: If the SVG cannot be parsed.
    """
    design = parse_svg_to_design(svg_path)

    # Convert to dict for YAML serialization
    design_dict = design.model_dump(exclude_none=True, by_alias=False)

    yaml_str = yaml.dump(design_dict, default_flow_style=False, sort_keys=False)

    if output_path:
        Path(output_path).write_text(yaml_str)

    return yaml_str
